### ISSUE TITLE
Use absolute url for images in feeds?

### ISSUE THREAD

**Issue by Sieboldianus** [Guts/mkdocs-rss-plugin#116]
First, stunning plugin, thanks so much for supporting the indie web!

I've added mkdocs-rss-plugin to my blog and it worked (almost) flawlessly.
https://du.nkel.dev/

The images shown in the description do not contain the full URL:
https://du.nkel.dev/feed_rss_created.xml

e.g.:
```
<img alt="hifi" src="img/hifi.jpg">
```

.. which is why they are not shown in preview.

Would it be possible to add this full url somwhere in the settings?

**Comment by Guts** [comment]
Hi @Sieboldianus,

Thanks for your interest and your kind message :).

To help, can you share the repository behind your blog with your mkdocs configuration file please?

**Comment by Sieboldianus** [comment]
Hi @Guts . Yes. I had this on my personal Gitlab, pushed it here to the public:
https://framagit.org/Sieboldianus/du.nkel.dev

**Comment by Guts** [comment]
Thanks.

I've tried to set up your site locally but I can't find requirements and i'm facing missing dependencies. WOuld you list them somewhere please to make debugging easier?

**Comment by Guts** [comment]
So, maybe it requires some clarification about how the plugin handle different images:

- you can set the channel (= the whole feed) image with the `image` settings. [ref doc](https://guts.github.io/mkdocs-rss-plugin/configuration/#channel-image).
- if you want an image per feed item (per page in case of blog), you need to specify the image to use within the page meta (YAML frontmatter): [ref doc](https://guts.github.io/mkdocs-rss-plugin/configuration/#item-image-enclosure)

From what I can see in your content, there is no specified image.

About the path to the image within page body, it's not related to the plugin but how the content is processed by mkdocs. The body is included as item description as almost raw HTML (or specified through page.meta.description).

**Comment by Sieboldianus** [comment]
> About the path to the image within page body, it's not related to the plugin but how the content is processed by mkdocs. The body is included as item description as almost raw HTML (or specified through page.meta.description).

Ok - thank you for the clarification and for looking into this. This makes sense - in this case I'd have to either 

1) use an absolute image URL for the first image in each post, as this may appear in the clipped summary of RSS .description.
2) or specify `page.meta.image` explicitly with a full image URL.  [page.meta.image](https://www.mkdocs.org/user-guide/writing-your-docs/#yaml-style-meta-data). In this case, the relative image in the RAW description would still appear broken, but it would be shown through the `page.meta.image`

I think this works for me. Many thanks! And kudos for this plugin. 👍
