### ISSUE TITLE
License change: GPL3 --> MIT. Committers agreement required.

### ISSUE THREAD

**Issue by Guts** [Guts/mkdocs-rss-plugin#117]
It has been reported to me that the license I chose at the beginning of the development ([GNU GPL v3](https://choosealicense.com/licenses/gpl-3.0/)) could cause problems for some projects or contributors.

I therefore propose to change to a more permissive license aligned with other projects in the Mkdocs ecosystem: [MIT](https://choosealicense.com/licenses/mit/).

For this, I need each committer to agree:

- [x] @liang2kl 
- [x] @prcr
- [x] @rmorshea 
- [x] @mondeja 
- [x] @dcode 
- [x] @timvink (not direct committer, but author of first git management)

Please, could you comment below to agree or disagree to this change?

**Comment by liang2kl** [comment]
I agree.

**Comment by dcode** [comment]
Agree

**Comment by mondeja** [comment]
I agree

**Comment by prcr** [comment]
I do agree.

**Comment by timvink** [comment]
Agree :)

**Comment by rmorshea** [comment]
Agree
