### ISSUE TITLE
Naming of RSS feed and autodetection by clients

### ISSUE THREAD

**Issue by surfer190** [Guts/mkdocs-rss-plugin#131]
I am using the [miniflux](https://miniflux.app/) RSS reader client.

When adding a feed it just asks for the base url - I give my mkdocs blog with this mkdocs-rss-plugin enabled.
It returns with an error message `Unable to find any subscription.`.

If I supply the `feed_rss_created.xml` or `feed_rss_updated.xml` urls it works.

Is this a problem with miniflux or with mkdocs?

**Comment by surfer190** [comment]
Looking at the code they have well [known URLS](https://github.com/miniflux/v2/blob/main/reader/subscription/finder.go#L143) as: 

```
	knownURLs := map[string]string{
		"/atom.xml": "atom",
		"/feed.xml": "atom",
		"/feed/":    "atom",
		"/rss.xml":  "rss",
		"/rss/":     "rss",
	}
```

Is there a way to ensure that `mkdocs-rss-plugin` exports the feed as expected above?

**Comment by Guts** [comment]
Hi @surfer190,

Thanks for your interest.

It's possible to reference the RSS feed through a HTML tag into the head. See: 
https://guts.github.io/mkdocs-rss-plugin/configuration/#integration

It might be interesting to allow customizing the output name of feeds in `mkdocs.yml`.

**Comment by Guts** [comment]
Hello @surfer190 ,

Any something new here or can we close it?
