### ISSUE TITLE
do not generate rss feed for draft posts

### ISSUE THREAD

**Issue by hellt** [Guts/mkdocs-rss-plugin#147]
Hi,
would it be possible to add a setting for not generating RSS feeds for markdown files that have

```
draft: true
```

in their frontmatter?

**Comment by Guts** [comment]
Hello,

Thanks for your interest.

Good idea and simple to implement. Done in #149.

Can you have a look please?

**Comment by hellt** [comment]
yes, looks good, thank you.
which version should this change be merged in so that I can pinpoint to it in my requirements?

PS> sorry for piggybacking on this, but I failed to find if there is an option to exclude "updates" feed from being generated?

**Comment by Guts** [comment]
>  which version should this change be merged in so that I can pinpoint to it in my requirements?

Released in https://github.com/Guts/mkdocs-rss-plugin/releases/tag/1.5.0


> PS> sorry for piggybacking on this, but I failed to find if there is an option to exclude "updates" feed from being generated?

Please create other issue with more details (use case, reasons, examples...).
