### ISSUE TITLE
fetch abstract up till well known `<!-- more -->` tag

### ISSUE THREAD

**Issue by hellt** [Guts/mkdocs-rss-plugin#151]
👋 
It is quite common for the markdown-based blog engines/themes to leverage the well known `<!-- more -->` tag to auto-generate the abstracts when the post is rendered.

It makes sense to expose an option for RSS plugin to fetch the post abstract up till that tag instead of a hard cut on the char limit.

**Comment by Guts** [comment]
Good idea.

I've no more time for this project these times. Feel free to push a PR or please wait until next avaibility.

**Comment by YDX-2147483647** [comment]
↑ Implemented in #173 2 weeks ago. :tada:

So let's close this issue?

**Comment by Guts** [comment]
Right, I though the merging the PR would close here.
