### ISSUE TITLE
Add JSON Feed support

### ISSUE THREAD

**Issue by notpushkin** [Guts/mkdocs-rss-plugin#165]
JSON has become the developers’ choice for APIs, and that developers will often go out of their way to avoid XML. RSS is nice as it has widespread support, but JSON is easier to use in ad-hoc applications, especially on frontend (point in case: I'm trying to add a small widget with latest articles from my blog right now).

Here's [specification](https://www.jsonfeed.org/version/1.1/) and [mapping from RSS](https://www.jsonfeed.org/mappingrssandatom/). Would you be interested in a PR implementing this?

**Comment by Guts** [comment]
Definetly yes!

**Comment by Guts** [comment]
Hey @notpushkin,

Still motivated?

**Comment by dngray** [comment]
Would love to see this added :+1:

**Comment by Guts** [comment]
Released as part of 1.12.0.
