### ISSUE TITLE
Language code might differ from RSS Spec

### ISSUE THREAD

**Issue by YDX-2147483647** [Guts/mkdocs-rss-plugin#176]
## Example

- [Mkdocs](https://www.mkdocs.org/user-guide/localizing-your-theme/#supported-locales): `en_US`. (underscore)
- [RSS Spec](https://validator.w3.org/feed/docs/rss2.html#optionalChannelElements): `en-US`. (hyphen)
> **Note**: RSS also accepted lowercase `en-us`.

## Explaination

- `theme.locale` of Mkdocs basically uses [ISO-639-1](https://en.wikipedia.org/wiki/ISO_639-1) _2-letter_ abbreviation (`en`), and may also include a territory suffix (`_US`).
- And the language code in RSS follows [W3C](https://www.w3.org/TR/REC-html40/struct/dirlang.html#langcodes) / [RFC 1766](https://www.ietf.org/rfc/rfc1766.txt) / _full_ ISO-639. I guess it's consistent with [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang), which follows [RFC 5646](https://datatracker.ietf.org/doc/html/rfc5646) (a newer version of RFC 1766).

Additionally, you can't write hyphen (`en-US`) in `mkdocs.yml`.

```shell
$ mkdocs build
ERROR    -  Config value 'theme': Invalid value for locale: expected only letters, got 'en-US'
Aborted with 1 Configuration Errors!
```

## Possible fix

(I can turn it into a PR if you want)

Change the following line in [`.util.Util.guess_locale`](https://github.com/Guts/mkdocs-rss-plugin/blob/769744e333613a318b8074ba34ac50df24abe36f/mkdocs_rss_plugin/util.py#L546-L567)

https://github.com/Guts/mkdocs-rss-plugin/blob/769744e333613a318b8074ba34ac50df24abe36f/mkdocs_rss_plugin/util.py#L563

to

```python
locale = mkdocs_config.get("theme")._vars.get("locale")
return f"{locale.language}-{locale.territory}"
```

**Comment by Guts** [comment]
Nice catch!

> (I can turn it into a PR if you want)

Please, feel free!
