### ISSUE TITLE
change feed url?

### ISSUE THREAD

**Issue by wez** [Guts/mkdocs-rss-plugin#249]
I'm migrating my blog from something else to mkdocs and my existing feed URL is simply `feed.xml`.
Since I'm hosting on Github Pages I don't have the ability to configure a server side redirect to `feed_rss_created.xml`.

Is there a way to configure the plugin to use my desired feed filename?
Alternatively, I'd love to hear other suggestions on how to resolve this without breaking existing links.

Thanks!

**Comment by Guts** [comment]
Hi @wez 

Sorry for the silence, I try to quantify the time I spend on my side-projects. Your requests was on the "roadmap" for long time.

It's now part of the https://github.com/Guts/mkdocs-rss-plugin/releases/tag/1.13.0 version. Enjoy and keep me update if it does the trick or note :).

**Comment by wez** [comment]
@Guts thanks! I'll try it out when I need need to make an update to the site!

**Comment by wez** [comment]
FWIW, I think I'm waiting on mkdocs-material to publish a new version with this new plugin version included before I can try this out. I'm in no rush!

**Comment by Guts** [comment]
@wez the RSS plugin is not shipped with Material :thinking:

**Comment by wez** [comment]
It is, they just haven't picked up your latest release yet
