### ISSUE TITLE
RSS plugin is not compatible with the categories of mkdocs-material blog

### ISSUE THREAD

**Issue by shenweiyan** [Guts/mkdocs-rss-plugin#266]
If I use the meta information "categories" in the mkdocs-material blog, the RSS plugin will generate an item for each category in the RSS XML. However, these items lack any other description information.

Example the a post:
```
---
date: 2024-04-09
categories:
    - General
authors:
  - "steven"
---

# Hello again world!


Hello world!
```

the `feed_rss_created.xml`:
```
<item>
  <title>General</title>
  <description><h1>General</h1></description>
  <pubDate>Tue, 09 Apr 2024 19:02:24 +0000</pubDate>
</item>
<item>
  <title>2024</title>
  <description><h1>2024</h1></description>
  <pubDate>Tue, 09 Apr 2024 19:02:24 +0000</pubDate>
</item>
```

Is there any way to remove the contents of `category` or `archive` items from the RSS feed? In my opinion, these empty items seem to serve no purpose. Thank you.

**Comment by shenweiyan** [comment]
I have solved this issue using the [`match_path`](https://guts.github.io/mkdocs-rss-plugin/configuration/#match_path-filter-pages-to-include-in-feed) parameter. Thanks again to the author for the excellent tool.

**Comment by Guts** [comment]
Hello @shenweiyan 

Thank you for your interest, creating an issue and auto-answering by searching the documentation :hugs:!
