### ISSUE TITLE
Min Python version to 3.10 is a problem for Netlify users

### ISSUE THREAD

**Issue by brabster** [Guts/mkdocs-rss-plugin#292]
Hi there,

I use Netlify to run my site and unfortunately they currently only support Python 3.8 https://docs.netlify.com/configure-builds/available-software-at-build-time/. I see a move to 3.10 min in my branch that I just synced with main and boom

![image](https://github.com/Guts/mkdocs-rss-plugin/assets/38702/373cba64-9c29-42ee-86c7-405d0bfa2361)

I'm not sure if updating past 3.8 is an option on Netlify, can't see a way. Had to pin back to an earlier commit to get back up and running. Might cause some problems if there's a lot of folks using it

**Comment by Guts** [comment]
Hello,

I did not planned to make this change and I would prefer to follow the EOL planning of Python releases as usual but I've been facing a bug with Mkdocs modern typed config objects. I've to take the time to investigate and file the issue upstream. 

I'm using Netlify to generate preview of my website on PR and I set the Python version in a runtime.txt file as described in https://docs.netlify.com/configure-builds/manage-dependencies/#python.

**Comment by brabster** [comment]
Oh could you share your Netlify runtime.txt? I tried contents '3.10" but it failed to build with the version not found. I figured you could only choose from the two versions Netlify mention but if I can pin it forward I'll do that!

**Comment by Guts** [comment]
https://github.com/geotribu/website/blob/master/runtime.txt

**Comment by brabster** [comment]
Hmm, that's exactly what I tried in my PR earlier this week, both 3.10 and 3.11 https://github.com/brabster/tw-site-mkdocs/pull/38/commits/0d7dbf436b8e37eb57aba0f816b20db8592caa2b, Netlify build broke

![failing netlify builf log mentioning Python 3.10](https://github.com/Guts/mkdocs-rss-plugin/assets/38702/da10455a-e429-44af-bf43-2a4a3b3f64be)

I don't see any significant different in what you do vs. what I do. If you get a minute could you share a Netlify deploy log, initializing step, under 3.10 for comparison? I'm currently stuck unable to sync to your main, I guess if you're going to flip it back to 3.8 compatible eventually it's not a big deal but I like to be up to date if possible

**Comment by Guts** [comment]
I've restored the compatibility with Python 3.8 and 3.9 in 1.3.4 with the help of https://github.com/mkdocs/mkdocs/issues/3753#issuecomment-2187180187.

Can you try it and give me feedback here please @brabster?

**Comment by brabster** [comment]
Hey @Guts thank you for making these changes. I've synced up to main now and my Netlify builds are working fine :pray:

I have mentioned this extra work you had to do on [the Netlify community forums](https://answers.netlify.com/t/the-current-python-version-3-8-is-very-old/96966/10?u=brabster).

**Comment by Guts** [comment]
> Hey @Guts thank you for making these changes. I've synced up to main now and my Netlify builds are working fine 🙏

Good news! Sorry again for the troubled temporary situation.

> I have mentioned this extra work you had to do on [the Netlify community forums](https://answers.netlify.com/t/the-current-python-version-3-8-is-very-old/96966/10?u=brabster).

Thanks you, I think it's valuable to give an overview of consequences of their choices regarding the build stack. But I have to say that I would make the same choices here: using the oldest supported Python version by default and allowing the end-user to pick up a specific version. Well, it's a shame if this last option does not work as expected.

If your website code is on GitHub (or GitLab), it's pretty fair simple to build and host on it. Not so optimized for sure (Netlify and Jamstack do an incredible work on static content) but mostly enough.
