### ISSUE TITLE
match_path is not OS agnostic

### ISSUE THREAD

**Issue by mvelikikh** [Guts/mkdocs-rss-plugin#321]
I used the following `match_path` and found that it resulted in an empty feed (no posts, just an RSS channel element) on Windows.
```yaml
rss:
  match_path: blog/posts/.*
```
At the same time, it was working properly on Linux.
The same issue was reported in #264 where it was found that it was working properly in Docker.

The real issue here is that the plugin uses `src_path` for pattern matching:
https://github.com/Guts/mkdocs-rss-plugin/blob/main/mkdocs_rss_plugin/plugin.py#L278
which results in '\\'-URLs on Windows, e.g. `blog\posts\something.md`.
MkDocs has already dealt with this issue by introducing `src_uri`: https://github.com/mkdocs/mkdocs/pull/2930
See also: 
- [src_path](https://www.mkdocs.org/dev-guide/api/#mkdocs.structure.files.File.src_path)
- [src_uri](https://www.mkdocs.org/dev-guide/api/#mkdocs.structure.files.File.src_uri)

I have tested that this solution works.
Raising this issue to get the fix done in the plugin.

**Comment by Guts** [comment]
Hello @mvelikikh 

Thanks for taking time to report and diagnose. Do you feel like doing the appropriate Pull Request to fix this?
