### ISSUE TITLE
Please add author support in rss feed item

### ISSUE THREAD

**Issue by krishansubudhi** [Guts/mkdocs-rss-plugin#34]
I saw the source code and figured out author support is not available. We want the blog authors name in the feed items. 
Can you add that please?

**Comment by Guts** [comment]
Could you further document your idea?

Should we use git contributor or page.meta.author?

How should the final tag be formatted?

It would really help to implement it quickly :)

**Comment by krishansubudhi** [comment]
We can add the feature through page.meta.author.
git contributor is also a good feature but page.meta.author should override git contributor. 
The formatting should be like [this](https://krishansubudhi.github.io/feed.xml)
```
  <author>
  <name>Krishan Subudhi</name>
  </author>
```

**Comment by Guts** [comment]
Thanks for your inputs.

> We can add the feature through page.meta.author.

I think we should take into an account that a page can have multiple authors, like co-contributors in git.

> git contributor is also a good feature but page.meta.author should override git contributor.

The plugin was first thought to use git information. Nevertheless, we can move forward more easily with the metadata of the page. Let's start by this side, then I'll see the git logic from @timvink plugins.

> The formatting should be like this
>
>  ```xml
>   <author>
>   <name>Krishan Subudhi</name>
>    </author>
> ```

Refering to the RSS standard to ensure our compliance. the author tag should have an email address:

- https://www.w3schools.com/XML/rss_tag_author.asp
- https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt

It'll be natural with the git log, but for the page.meta it's on the page writer.

**Comment by krishansubudhi** [comment]
Thanks Julien.
