### ISSUE TITLE
Semantic versioning support

### ISSUE THREAD

**Issue by lyz-code** [Guts/mkdocs-rss-plugin#42]
Hi, first of all thanks for the plugin, I've had this need for a long time. 

Even though the current functionality works flawlessly, I think we can use the [semantic
versioning](https://semver.org/) functionality to make the RSS feed even richer.

The idea is to create commits following [a specific format](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines) that describes what kind of change you're making. I've [been following this practice](https://github.com/lyz-code/blue-book/commits/master) for a while with the following personal commit convention:

```
{type_of_change}({file_changed}): {short_description}
{full_description}
```

Where:
* `type_of_change` is one of:
  * `feat`: Add new content to the repository, it can be a new file or new content on an
    existent file.
  * `fix`: Correct existing content.
  * `style`: Correct grammar, orthography or broken links.
  * `ci`: Change the continuous integration pipelines.
  * `chore`: Update the python dependencies required to build the site.

* `file_changed`: name of the file changed (without the `.md` extension)

For example: [a single feat
commit](https://github.com/lyz-code/blue-book/commit/5eb3f57da4de99e58bf25ab4b5e24fbb007f7319) or
[a multientry commit](https://github.com/lyz-code/blue-book/commit/53f7b1f67bc7aa2c654e8bfe286d8175e099747b)

With this information in the git log we could generate RSS feed entries whose:

* Title is taken from `short_description`.
* Body is taken from `full_description`.
* The link to the article can be built from `file_changed`.
* Only `feat` and `fix` entries are evaluated (no one wants to receive an rss
notification of a typo fix in an article).
* An entry will be created for each change, so multientry commits will have many entries.

We could also support a "newsletter" mode inspired by
[python-semantic-release](https://python-semantic-release.readthedocs.io/en/latest/commit-log-parsing.html)
and
[commitizen bump](https://github.com/commitizen-tools/commitizen), where each time you
make a release in your documentation, all the changes in your repo since the last git
tag are processed into a single entry where the changes are grouped by `file_changed`.

I know the proposal will add complexity to the plugin, and I understand why you wouldn't
want that, but if you are interested, I'd like to help building it.

**Comment by Guts** [comment]
Hi @lyz-code, 

Thanks for your interest and for taking time to write your proposal.

I understand that it's tempting to adapt different tools to a commit convention (as interesting as it is), but I think that it's not in the functional scope of this actual plugin which is really oriented for MkDocs content and whose use of the git log is only a part of its mechanisms.

If you still want to add your logic, feel free to make a PR . I'll review it but keep in mind that you'll have to ensure that it doesn't break the actual behavior, keeping it independent of any commit convention.

**Comment by lyz-code** [comment]
I'm glad that you want to accept the functionality as long as it doesn't break the existent code base.

Once I have a solid implementation plan, I'll share it here with you to gather your insights.

Thanks!

**Comment by lyz-code** [comment]
Hi @Guts , I've got the first draft of what I want and how to implement it.

* [MkDocs plugin architecture](https://share.riseup.net/#vk2yP7u7JsnJp95BeWEd0g)
* [Reasoning behind the need of this change](https://share.riseup.net/#wNjZ37-kGKSqjgpOShNn0A)

And probably in the future I'll have a [changelog mode](https://share.riseup.net/#Gn-N2YfSnLBNN52zDQDl_Q) too.

I feel that maybe I plan to add multiple complex workflow that only shares the logic of RSS
generation and git parsing with mkdocs-rss-plugin, so creating a new plugin could make more sense. 

If you like the proposal and are still happy maintaining it with me, I can still develop in inside mkdocs-rss-plugin

**Comment by Guts** [comment]
Got this error trying to open your links:

![image](https://user-images.githubusercontent.com/1596222/107629413-5e529f80-6c62-11eb-9b6a-45bf1a984141.png)

**Comment by lyz-code** [comment]
It seems they expired quite fast, I've uploaded a WIP of the plan [here](https://github.com/lyz-code/mkdocs-newsletter/tree/feat/initial_iteration/docs/adr)

**Comment by Guts** [comment]
Nice work and specifications!
So finally, you decided to make a plugin apart?

**Comment by lyz-code** [comment]
I've started the development as a separate plugin because it was the easiest way to start moving, but it doesn't need to end like that.

Do you like the shape it's getting? meaning:

* The problems I'm trying to solve
* How I'm solving them.
* How I'm documenting the development.
* The way I'm testing the code.
* The project structure.

And do you think it's closely related to mkdocs-rss-plugin to a point that they both belong to the same repository?

If you do, we can think of merging forces into one project.

**Comment by Guts** [comment]
I think your project is much larger than this actual plugin which is designed to be minimalist and focused on generating RSS feeds without constraining the commits.

The repository of your project already has a lot of dependencies, goals (newsletter, APIs...)i and constraints. So I think both plugins can live independently. This way, end users will have the choice according to their needs.

Be sure, I will follow the evolution of your plugin with attention!

> Creating an RSS entry for each change, as mkdocs-rss-plugin is not a valid solution [...]

From [this file](https://github.com/lyz-code/mkdocs-newsletter/blob/feat/initial_iteration/docs/adr/00X-rss-feed-creation.md#update-the-rss-feed). Did you see that in the actual plugin, there are 2 feeds:

- one for created contents (according page.meta.date or git log),
- another one for updated contents.

So the end-user can subscribe to the preferred feed and because the entry id is not changing, there is no new notification  for a typo update, no?

**Comment by lyz-code** [comment]
Damn, after reading your quote, the phrase sounded quite harsh. Sorry for that, I'm fixing it right away. 

What I meant is that sometimes I update files because I add new content, make a fix on something that has become deprecated or superseeded, but other times I update them for typos. In the updated feed all these changes will show up, when I only want to add the non typo ones.

I agree on the scope difference, and that it makes sense to keep both projects alive and independent. I'll close the issue now, but will let you know here when it's ready in case you want to try it :)

Thanks for your time

**Comment by lyz-code** [comment]
Hi @Guts, I've finished the first usable version of [mkdocs-newsletter](https://lyz-code.github.io/mkdocs-newsletter/) in case you want to take a look :)

**Comment by Guts** [comment]
> Hi @Guts, I've finished the first usable version of [mkdocs-newsletter](https://lyz-code.github.io/mkdocs-newsletter/) in case you want to take a look :)

Good to read! I'll try to have a look during the next few days.
