### ISSUE TITLE
Need exclude options

### ISSUE THREAD

**Issue by WAY29** [Guts/mkdocs-rss-plugin#72]
I need exclude options to exclude some pages that generated by ohter plugins, like [mkdocs-plugin-tags](https://github.com/jldiaz/mkdocs-plugin-tags)

**Comment by Guts** [comment]
You probably need to use the `match_path` option: https://guts.github.io/mkdocs-rss-plugin/configuration/#filter-pages

**Comment by Guts** [comment]
@WAY29 did you find out? Can we close here?
