### ISSUE TITLE
[Doubt] Does it conform to RSS 2.0 spec?

### ISSUE THREAD

**Issue by IMG-PRCSNG** [Guts/mkdocs-rss-plugin#9]
I find that in this [w3schools reference](https://www.w3schools.com/xml/rss_tag_enclosure.asp) that length is a required attribute. I tried parsing it with the [ruby RSS parser](https://github.com/ruby/rss) and it fails validation with MissingAttributeError for `length`.

**Comment by Guts** [comment]
Hi. Thanks for trying this plugin and taking time to report.


Nice catch 👍! Indeed, because the image may be remote and unreachable, I had opted for a quick but incomplete solution. I'll try to fix it and validate RSS during CI.
